spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/estudos
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
  sql:
    init:
      platform: postgres
  flyway:
    baseline-on-migrate: true
springdoc:
  pathsToMatch: /api/**/v1/**
  swagger-ui:
    use-root-path: true